/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Jfmm-10' at '16/02/16 18:17' with Gradle 2.6
 *
 * @author Jfmm-10, @date 16/02/16 18:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
